SELECT TOP (1000) [Build_ID]
      ,[playerName]
      ,[Position]
      ,[Build]
      ,[closeShot]
      ,[drivingLayup]
      ,[drivingDunk]
      ,[standingDunk]
      ,[postControl]
      ,[middy]
      ,[3s]
      ,[freeThrow]
      ,[passAccuracy]
      ,[ballHandle]
      ,[speedWithBall ]
      ,[interiorDefense ]
      ,[perimeterDefense]
      ,[steal]
      ,[block]
      ,[offensiveRebound]
      ,[defensiveRebound]
      ,[speed]
      ,[acceleration]
      ,[strength]
      ,[vertical]
      ,[Stamina]
  FROM [RIP_Academy777].[dbo].[buildAttributes]
